version: '3.8'
services:
  node:
    container_name: frontend_react
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/app